fix: pre-commits

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,30 +1,19 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-echo '- formating your code ...'
-
-npm run format
-
-echo '- checking your code ...'
-
-npm run check-format ||
+echo '- Checking your Typescript code ...'
+pnpm run check-types ||
 (
-    echo '❌ Prettier Check Failed.';
+    echo '❌ Typescript Check Failed.';
     false;
 )
 
-npm run check-lint ||
+echo '- Running your tests ...'
+pnpm test ||
 (
-    echo '❌ ESLint Check Failed.'
-    false; 
-)
-
-npm run check-types ||
-(
-    echo '❌ Failed Type check.'
+    echo '❌ Your Tests Failed.';
     false;
 )
 
-echo '✅ Done.'
-
-yarn lint-staged
+echo '- Checking your code ...'
+pnpm lint-staged
